### ISSUE TITLE
face enhance model load failed

### ISSUE THREAD

**Issue by VSycx** [microsoft/Bringing-Old-Photos-Back-to-Life#11]
thanks for the fantastic works!
I was testing the face enhance model with my own dataset which struct as follows:
dataset
--  xyz
     -- test_A (image to be enhanced, 256*256, .png format)
     -- test_B (empty as no labels were provided)

When I run test_face.py I got the following errors:
RuntimeError: Error(s) in loading state_dict for SPADEGenerator:
     size mismatch for fc.weight : copying a param with shape torch.Size([1024,3,3,3]) from checkpoint, the shape in current model is torch.Size([1024,184,3,3]).
     similar errors for some other weights i.e., head_0_norm_0.mlp_shared.0.weight

love to hear from u guys
cheers

**Comment by raywzy** [comment]
Hi,
Have you tried to directly input the test images (it also could be faces) to the whole pipeline instead of single face enhancement module? The face model is jointly trained with previous network, so I guess the whole pipeline will lead to a better results.  Just try `python run.py --input_folder [face_path] --output_folder [xx] --GPU 0` and see if it will work :)

**Comment by VSycx** [comment]
cheers, solved!
