### ISSUE TITLE
Test grayscale input image? (Colorization effects)

### ISSUE THREAD

**Issue by vztu** [microsoft/Bringing-Old-Photos-Back-to-Life#146]
Hi authors, I am trying to test the pretrained model on grayscale images. What I did was first copy grayscale images to rgb channels then used the code to test the fake rgb image:
```
# Psudocode: gray to rgb
for img in [test_image_folder_path]:
  img_fakergb = gray2rgb(img)
  imwrite(img_fakergb, [test_image_folder_path])
```

```
python run.py --input_folder [test_image_folder_path] \
              --output_folder [output_path] \
              --GPU 0
```

However, I got very bad output (still a very gray image, no colorization at all). Could you tell me how to bring "gray" old photos back to life? 

--- 
input image:
![0804](https://user-images.githubusercontent.com/43280278/113959241-1b3b2580-97e8-11eb-8f9e-58834d9e8b80.png)
output image:
![0804](https://user-images.githubusercontent.com/43280278/113959172-03fc3800-97e8-11eb-9951-787d46c3b7cb.png)

**Comment by zhangmozhe** [comment]
Possibly you are processing a large resolution photo, while our model is trained on 256x256 images. You can try to rescale the photo a little bit and try again.

This project is focusing on restoring photos rather than colorization, as the two processing can be cascaded. For colorization, you can refer to our another work, https://github.com/zhangmozhe/Deep-Exemplar-based-Video-Colorization.
