### ISSUE TITLE
UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. 

### ISSUE THREAD

**Issue by eltechno** [microsoft/Bringing-Old-Photos-Back-to-Life#18]
hi ! i did try to run the code with no success using pytorch 1.4 and 1.6 with python 3 im running Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1025-aws x86_64v) CUDA 10.1 and Intel MKL

but i always have the same results no FACES, is any advise to fix this issues ?

============================================================================

Running Stage 3: Face Enhancement
The main GPU is
0
dataset [FaceTestDataset] of size 12 was created
The size of the latent vector size is [8,8]
Network [SPADEGenerator] was created. Total number of parameters: 92.1 million. To see the architecture, do print(network).
hi :)
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/functional.py:1340: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Finish Stage 3 ...

**Comment by zhangmozhe** [comment]
Do you mean the warning of failing to detect faces?

**Comment by eltechno** [comment]
> Do you mean the warning of failing to detect faces?

@zhangmozhe please nevermind my fault, and many thanks for reply back

**Comment by zhangmozhe** [comment]
Possibly the photo does not contain faces or the photo is severely degraded so the faces are hard to be detected. We currently use dlib library for face detection. 

Should there is more question, please reopen the issue.

**Comment by unicode6674** [comment]
同样， mac 


initializing the dataloader
model weights loaded
directory of testing image: /Users/jinhuihou/Desktop/research/Bringing-Old-Photos-Back-to-Life/test_images/old_w_scratch
processing a.png
processing b.png
processing c.png
processing d.png
processing wym.png
You are using NL + Res
Now you are processing a.png
/Users/jinhuihou/Desktop/research/Bringing-Old-Photos-Back-to-Life/venv/lib/python3.9/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
Now you are processing b.png
Now you are processing c.png
Now you are processing d.png
Now you are processing wym.png
zsh: terminated  python GUI.py
