### ISSUE TITLE
pip install -r requirements.txt fails on Debian

### ISSUE THREAD

**Issue by nigelhorne** [microsoft/Bringing-Old-Photos-Back-to-Life#194]
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/user/1000/pip-install-589xesun/dlib_42a1f8a9382e42518d50a243a456bce8/setup.py'"'"'; __file__='"'"'/tmp/user/1000/pip-install-589xesun/dlib_42a1f8a9382e42518d50a243a456bce8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/user/1000/pip-wheel-f7czvpn_
       cwd: /tmp/user/1000/pip-install-589xesun/dlib_42a1f8a9382e42518d50a243a456bce8/
  Complete output (8 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
  running build_ext
  
  ERROR: CMake must be installed to build dlib
  
  ----------------------------------------
  ERROR: Failed building wheel for dlib

installing cmake, of course, fixed this, so this is a minor bug for improving the documentation.

**Comment by KeygenLLC** [comment]
Same happens on mac os for me on mojave and big sur using anaconda.

I typically follow this order to avoid running into failures with dlib or opencv-python after I setup the initial python env:

- `conda create -n MYENV python=3.x.x`
- `pip install cmake`
- `pip install --upgrade pip setuptools wheel`
- `pip install opencv-python==4.2.0.34` (this version seems to always work)
- `pip install dlib -vvv`

Once these are setup, I run the requirements file. Seems to help alleviate the failures in almost every case. Should help even if you aren't using anaconda.

dlib can take a while to install, so long that you might think it failed. I would advise using `pip install dlib -vvv` so you can make sure it didn't fail by keeping track of everything it's doing. opencv-python hangs for me and never finishes unless I specifically state which version to use. Latest version typically still fails, but might be because I'm not using latest macOS.

**Comment by kj-1024** [comment]
如果安装dlib失败，报错信息ERROR: Failed building wheel for dlib。
可以直接使用以下步骤：
 1. 直接从源代码安装dlib： 如果你已经尝试了使用pip安装dlib并且失败了，你可以尝试从dlib的GitHub仓库直接安装：
    git clone https://github.com/davisking/dlib.git
    cd dlib
    # 确保你的conda环境已经激活
    conda activate myenv
    python setup.py install
  2.执行pip install -r requirements.txt
  3.报错消失，正常运行
